export const GET_ALL_PUBLIC_FOODS_REQUEST = "GET_ALL_PUBLIC_FOODS_REQUEST";
export const GET_ALL_PUBLIC_FOODS_SUCCESS = "GET_ALL_PUBLIC_FOODS_SUCCESS";
export const GET_ALL_PUBLIC_FOODS_FAILURE = "GET_ALL_PUBLIC_FOODS_FAILURE";