// src/State/Rating/ActionType.js

export const ADD_RATING_REQUEST = "ADD_RATING_REQUEST";
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS";
export const ADD_RATING_FAILURE = "ADD_RATING_FAILURE";

export const GET_RATINGS_REQUEST = "GET_RATINGS_REQUEST";
export const GET_RATINGS_SUCCESS = "GET_RATINGS_SUCCESS";
export const GET_RATINGS_FAILURE = "GET_RATINGS_FAILURE";

export const GET_RATINGS_PUBLIC_REQUEST = "GET_RATINGS_PUBLIC_REQUEST";
export const GET_RATINGS_PUBLIC_SUCCESS = "GET_RATINGS_PUBLIC_SUCCESS";
export const GET_RATINGS_PUBLIC_FAILURE = "GET_RATINGS_PUBLIC_FAILURE";

export const UPDATE_RATING_REQUEST = "UPDATE_RATING_REQUEST";
export const UPDATE_RATING_SUCCESS = "UPDATE_RATING_SUCCESS";
export const UPDATE_RATING_FAILURE = "UPDATE_RATING_FAILURE";

export const DELETE_RATING_REQUEST = "DELETE_RATING_REQUEST";
export const DELETE_RATING_SUCCESS = "DELETE_RATING_SUCCESS";
export const DELETE_RATING_FAILURE = "DELETE_RATING_FAILURE";

export const UPDATE_VISIBILITY_RATING_REQUEST = "UPDATE_VISIBILITY_RATING_REQUEST";
export const UPDATE_VISIBILITY_RATING_SUCCESS = "UPDATE_VISIBILITY_RATING_SUCCESS";
export const UPDATE_VISIBILITY_RATING_FAILURE = "UPDATE_VISIBILITY_RATING_FAILURE";