// ActionType.js
export const REQUEST_RIDE = "REQUEST_RIDE";
export const REQUEST_RIDE_SUCCESS = "REQUEST_RIDE_SUCCESS";
export const REQUEST_RIDE_FAILURE = "REQUEST_RIDE_FAILURE";

export const FIND_RIDE_BY_ID_REQUEST = "FIND_RIDE_BY_ID_REQUEST";
export const FIND_RIDE_BY_ID_SUCCESS = "FIND_RIDE_BY_ID_SUCCESS";
export const FIND_RIDE_BY_ID_FAILURE = "FIND_RIDE_BY_ID_FAILURE";

export const ACCEPT_RIDE_REQUEST = "ACCEPT_RIDE_REQUEST";
export const ACCEPT_RIDE_SUCCESS = "ACCEPT_RIDE_SUCCESS";
export const ACCEPT_RIDE_FAILURE = "ACCEPT_RIDE_FAILURE";

export const DECLINE_RIDE_REQUEST = "DECLINE_RIDE_REQUEST";
export const DECLINE_RIDE_SUCCESS = "DECLINE_RIDE_SUCCESS";
export const DECLINE_RIDE_FAILURE = "DECLINE_RIDE_FAILURE";

export const START_RIDE_REQUEST = "START_RIDE_REQUEST";
export const START_RIDE_SUCCESS = "START_RIDE_SUCCESS";
export const START_RIDE_FAILURE = "START_RIDE_FAILURE";

export const COMPLETE_RIDE_REQUEST = "COMPLETE_RIDE_REQUEST";
export const COMPLETE_RIDE_SUCCESS = "COMPLETE_RIDE_SUCCESS";
export const COMPLETE_RIDE_FAILURE = "COMPLETE_RIDE_FAILURE";

export const CANCEL_RIDE_REQUEST = "CANCEL_RIDE_REQUEST";
export const CANCEL_RIDE_SUCCESS = "CANCEL_RIDE_SUCCESS";
export const CANCEL_RIDE_FAILURE = "CANCEL_RIDE_FAILURE";

export const FIND_ALL_RIDE_REQUEST = "FIND_ALL_RIDE_REQUEST";
export const FIND_ALL_RIDE_SUCCESS = "FIND_ALL_RIDE_SUCCESS";
export const FIND_ALL_RIDE_FAILURE = "FIND_ALL_RIDE_FAILURE";