
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER__REQUEST = "CREATE_ORDER__REQUEST";
export const CREATE_ORDER__SUCCESS = "CREATE_ORDER__SUCCESS";
export const CREATE_ORDER__FAILURE = "CREATE_ORDER__FAILURE";

export const CONFIRM_ORDER_REQUEST = "CONFIRM_ORDER_REQUEST";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_FAILURE = "CONFIRM_ORDER_FAILURE";

export const GET_USERS_ORDERS_REQUEST = "GET_USERS_ORDERS_REQUEST";
export const GET_USERS_ORDERS_SUCCESS = "GET_USERS_ORDERS_SUCCESS";
export const GET_USERS_ORDERS_FAILURE = "GET_USERS_ORDERS_FAILURE";

export const GET_USERS_NOTIFICATION_REQUEST = "GET_USERS_NOTIFICATION_REQUEST";
export const GET_USERS_NOTIFICATION_SUCCESS = "GET_USERS_NOTIFICATION_SUCCESS";
export const GET_USERS_NOTIFICATION_FAILURE = "GET_USERS_NOTIFICATION_FAILURE";

export const UPDATE_ORDER_ISPAY_REQUEST = "UPDATE_ORDER_ISPAY_REQUEST";
export const UPDATE_ORDER_ISPAY_SUCCESS = "UPDATE_ORDER_ISPAY_SUCCESS";
export const UPDATE_ORDER_ISPAY_FAILURE = "UPDATE_ORDER_ISPAY_FAILURE";

export const REFUND_ORDER_REQUEST = "REFUND_ORDER_REQUEST";
export const REFUND_ORDER_SUCCESS = "REFUND_ORDER_SUCCESS";
export const REFUND_ORDER_FAILURE = "REFUND_ORDER_FAILURE";

export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const SEND_OTP_VIA_EMAIL_REQUEST = "SEND_OTP_VIA_EMAIL_REQUEST";
export const SEND_OTP_VIA_EMAIL_SUCCESS = "SEND_OTP_VIA_EMAIL_SUCCESS";
export const SEND_OTP_VIA_EMAIL_FAILURE = "SEND_OTP_VIA_EMAIL_FAILURE";

export const VERIFY_OTP_VIA_EMAIL_REQUEST = "VERIFY_OTP_VIA_EMAIL_REQUEST";
export const VERIFY_OTP_VIA_EMAIL_SUCCESS = "VERIFY_OTP_VIA_EMAIL_SUCCESS";
export const VERIFY_OTP_VIA_EMAIL_FAILURE = "VERIFY_OTP_VIA_EMAIL_FAILURE";


