export const REGISTER_DRIVER_REQUEST = "REGISTER_DRIVER_REQUEST";
export const REGISTER_DRIVER_SUCCESS = "REGISTER_DRIVER_SUCCESS";
export const REGISTER_DRIVER_FAILURE = "REGISTER_DRIVER_FAILURE";

export const GET_AVAILABLE_DRIVERS_REQUEST = "GET_AVAILABLE_DRIVERS_REQUEST";
export const GET_AVAILABLE_DRIVERS_SUCCESS = "GET_AVAILABLE_DRIVERS_SUCCESS";
export const GET_AVAILABLE_DRIVERS_FAILURE = "GET_AVAILABLE_DRIVERS_FAILURE";

export const FIND_NEAREST_DRIVER_REQUEST = "FIND_NEAREST_DRIVER_REQUEST";
export const FIND_NEAREST_DRIVER_SUCCESS = "FIND_NEAREST_DRIVER_SUCCESS";
export const FIND_NEAREST_DRIVER_FAILURE = "FIND_NEAREST_DRIVER_FAILURE";

export const GET_DRIVER_PROFILE_REQUEST = "GET_DRIVER_PROFILE_REQUEST";
export const GET_DRIVER_PROFILE_SUCCESS = "GET_DRIVER_PROFILE_SUCCESS";
export const GET_DRIVER_PROFILE_FAILURE = "GET_DRIVER_PROFILE_FAILURE";

export const GET_DRIVER_CURRENT_RIDE_REQUEST = "GET_DRIVER_CURRENT_RIDE_REQUEST";
export const GET_DRIVER_CURRENT_RIDE_SUCCESS = "GET_DRIVER_CURRENT_RIDE_SUCCESS";
export const GET_DRIVER_CURRENT_RIDE_FAILURE = "GET_DRIVER_CURRENT_RIDE_FAILURE";

export const GET_ALLOCATED_RIDES_REQUEST = "GET_ALLOCATED_RIDES_REQUEST";
export const GET_ALLOCATED_RIDES_SUCCESS = "GET_ALLOCATED_RIDES_SUCCESS";
export const GET_ALLOCATED_RIDES_FAILURE = "GET_ALLOCATED_RIDES_FAILURE";

export const FIND_DRIVER_BY_ID_REQUEST = "FIND_DRIVER_BY_ID_REQUEST";
export const FIND_DRIVER_BY_ID_SUCCESS = "FIND_DRIVER_BY_ID_SUCCESS";
export const FIND_DRIVER_BY_ID_FAILURE = "FIND_DRIVER_BY_ID_FAILURE";

export const COMPLETED_RIDES_REQUEST = "COMPLETED_RIDES_REQUEST";
export const COMPLETED_RIDES_SUCCESS = "COMPLETED_RIDES_SUCCESS";
export const COMPLETED_RIDES_FAILURE = "COMPLETED_RIDES_FAILURE";

export const UPDATE_DRIVER_REQUEST = "UPDATE_DRIVER_REQUEST";
export const UPDATE_DRIVER_SUCCESS = "UPDATE_DRIVER_SUCCESS";
export const UPDATE_DRIVER_FAILURE = "UPDATE_DRIVER_FAILURE";

export const DELETE_DRIVER_IMAGE_REQUEST = "DELETE_DRIVER_IMAGE_REQUEST";
export const DELETE_DRIVER_IMAGE_SUCCESS = "DELETE_DRIVER_IMAGE_SUCCESS";
export const DELETE_DRIVER_IMAGE_FAILURE = "DELETE_DRIVER_IMAGE_FAILURE";
