export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const GET_EVENTS_BY_RESTAURANT_REQUEST = "GET_EVENTS_BY_RESTAURANT_REQUEST";
export const GET_EVENTS_BY_RESTAURANT_SUCCESS = "GET_EVENTS_BY_RESTAURANT_SUCCESS";
export const GET_EVENTS_BY_RESTAURANT_FAILURE = "GET_EVENTS_BY_RESTAURANT_FAILURE";

export const GET_EVENT_BY_ID_REQUEST = "GET_EVENT_BY_ID_REQUEST";
export const GET_EVENT_BY_ID_SUCCESS = "GET_EVENT_BY_ID_SUCCESS";
export const GET_EVENT_BY_ID_FAILURE = "GET_EVENT_BY_ID_FAILURE";

export const ADD_EVENT_TO_FAVORITE_REQUEST = "ADD_EVENT_TO_FAVORITE_REQUEST";
export const ADD_EVENT_TO_FAVORITE_SUCCESS = "ADD_EVENT_TO_FAVORITE_SUCCESS";
export const ADD_EVENT_TO_FAVORITE_FAILURE = "ADD_EVENT_TO_FAVORITE_FAILURE";

export const GET_EVENT_FAVORITED_BY_ID_REQUEST = "GET_EVENT_FAVORITED_BY_ID_REQUEST";
export const GET_EVENT_FAVORITED_BY_ID_SUCCESS = "GET_EVENT_FAVORITED_BY_ID_SUCCESS";
export const GET_EVENT_FAVORITED_BY_ID_FAILURE = "GET_EVENT_FAVORITED_BY_ID_FAILURE";

export const TOGGLE_AVAILABLE_REQUEST = "TOGGLE_AVAILABLE_REQUEST";
export const TOGGLE_AVAILABLE_SUCCESS = "TOGGLE_AVAILABLE_SUCCESS";
export const TOGGLE_AVAILABLE_FAILURE = "TOGGLE_AVAILABLE_FAILURE";

export const ALL_EVENTS_OF_FAVORITED_RESTAURANTS_REQUEST = "ALL_EVENTS_OF_FAVORITED_RESTAURANTS_REQUEST";
export const ALL_EVENTS_OF_FAVORITED_RESTAURANTS_SUCCESS = "ALL_EVENTS_OF_FAVORITED_RESTAURANTS_SUCCESS";
export const ALL_EVENTS_OF_FAVORITED_RESTAURANTS_FAILURE = "ALL_EVENTS_OF_FAVORITED_RESTAURANTS_FAILURE";

export const GET_ALL_PUBLIC_EVENTS_REQUEST = "GET_ALL_PUBLIC_EVENTS_REQUEST";
export const GET_ALL_PUBLIC_EVENTS_SUCCESS = "GET_ALL_PUBLIC_EVENTS_SUCCESS";
export const GET_ALL_PUBLIC_EVENTS_FAILURE = "GET_ALL_PUBLIC_EVENTS_FAILURE";

export const GET_LIST_USERS_BY_EVENT_REQUEST = "GET_LIST_USERS_BY_EVENT_REQUEST";
export const GET_LIST_USERS_BY_EVENT_SUCCESS = "GET_LIST_USERS_BY_EVENT_SUCCESS";
export const GET_LIST_USERS_BY_EVENT_FAILURE = "GET_LIST_USERS_BY_EVENT_FAILURE";

export const IS_USER_CHECKIN_EVENT_REQUEST = "IS_USER_CHECKIN_EVENT_REQUEST";
export const IS_USER_CHECKIN_EVENT_SUCCESS = "IS_USER_CHECKIN_EVENT_SUCCESS";
export const IS_USER_CHECKIN_EVENT_FAILURE = "IS_USER_CHECKIN_EVENT_FAILURE";

export const GET_LIST_CHECKIN_REQUEST = "GET_LIST_CHECKIN_REQUEST";
export const GET_LIST_CHECKIN_SUCCESS = "GET_LIST_CHECKIN_SUCCESS";
export const GET_LIST_CHECKIN_FAILURE = "GET_LIST_CHECKIN_FAILURE";

export const GET_EVENT_ATTENDEES_ANALYTICS_REQUEST = "GET_EVENT_ATTENDEES_ANALYTICS_REQUEST";
export const GET_EVENT_ATTENDEES_ANALYTICS_SUCCESS = "GET_EVENT_ATTENDEES_ANALYTICS_SUCCESS";
export const GET_EVENT_ATTENDEES_ANALYTICS_FAILURE = "GET_EVENT_ATTENDEES_ANALYTICS_FAILURE";
